### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by eshapard** [TariqAHassan/EasyMoney#11]
```
>>> from easymoney.money import EasyPeasy
>>> ep = EasyPeasy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/easymoney/money.py", line 106, in __init__
    self._cpi_dict = world_bank_pull(return_as='dict')
  File "/usr/local/lib/python3.6/dist-packages/easymoney/sources/world_bank_interface.py", line 87, in world_bank_pull
    raw_data = wbdata.get_data(indicator)
  File "/usr/local/lib/python3.6/dist-packages/wbdata/api.py", line 167, in get_data
    data = fetcher.fetch(query_url, args)
  File "/usr/local/lib/python3.6/dist-packages/wbdata/fetcher.py", line 163, in fetch
    raw_response = fetch_url(query_url)
  File "/usr/local/lib/python3.6/dist-packages/wbdata/fetcher.py", line 135, in fetch_url
    raise ValueError
ValueError
```

Any ideas?

**Comment by TariqAHassan** [comment]
Hey @eshapard 

Sorry for the delay.

The problem you experiences was due to [this](https://github.com/OliverSherouse/wbdata/issues/56) bug in wbdata.
It has been resolved now, so the problem should be resolved in you reinstall easymoney. Please let me know if you have any trouble.

**Comment by eshapard** [comment]
Thanks, Tariq!

I did a reinstall with `pip3 install --upgrade --force-reinstall` and 
it's working now.

Excerpts from Tariq Hassan's message of June 28, 2020 8:09 pm:
